# Generated by Django 6.1 on 2026-09-30 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandetpdetail',
            name='id_prestataire',
            field=models.ForeignKey(blank=True, db_column='id_prestataire', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.prestataire'),
        ),
        migrations.AddField(
            model_name='demandetpdetail',
            name='id_sous_acte',
            field=models.ForeignKey(blank=True, db_column='id_sous_acte', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.sousacte'),
        ),
    ]
