# Generated by Django 6.1 on 2026-10-04 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_demandetpdetail_id_prestataire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampPersonnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entite', models.CharField(choices=[('ADHERENT', 'Adhérent'), ('AYANT_DROIT', 'Ayant droit'), ('PRESTATAIRE', 'Prestataire'), ('SOUSCRIPTEUR', 'Souscripteur'), ('CONTRAT', 'Contrat'), ('FACTURE', 'Facture'), ('DEMANDE_TP', 'Demande TP')], max_length=30)),
                ('nom_technique', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=200)),
                ('type_champ', models.CharField(choices=[('TEXT', 'Texte court'), ('TEXT_LONG', 'Texte long'), ('NUMBER', 'Nombre'), ('DECIMAL', 'Nombre décimal'), ('DATE', 'Date'), ('BOOLEAN', 'Oui / Non'), ('CHOICE', 'Liste de choix')], max_length=20)),
                ('obligatoire', models.BooleanField(default=False)),
                ('valeur_defaut', models.CharField(blank=True, max_length=200, null=True)),
                ('choix_possibles', models.TextField(blank=True, help_text='Pour le type CHOICE : une valeur par ligne', null=True)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('statut', models.CharField(default='ACTIF', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'champ_personnalise',
                'ordering': ['entite', 'ordre_affichage', 'id'],
                'managed': True,
                'unique_together': {('entite', 'nom_technique')},
            },
        ),
        migrations.CreateModel(
            name='ValeurChampPersonnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_enregistrement', models.BigIntegerField()),
                ('valeur', models.TextField(blank=True, null=True)),
                ('champ', models.ForeignKey(db_column='id_champ', on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='core.champpersonnalise')),
            ],
            options={
                'db_table': 'valeur_champ_personnalise',
                'managed': True,
                'indexes': [models.Index(fields=['champ', 'id_enregistrement'], name='valeur_cham_id_cham_4d252c_idx')],
                'unique_together': {('champ', 'id_enregistrement')},
            },
        ),
    ]
