# Generated by Django 6.1 on 2026-10-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_champpersonnalise_valeurchamppersonnalise'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantieacte',
            name='mode_calcul',
            field=models.CharField(choices=[('POURCENTAGE', 'Pourcentage du montant'), ('FORFAIT', 'Montant fixe'), ('FRAIS_REELS', 'Frais réels (sans calcul)')], default='POURCENTAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='garantieacte',
            name='montant_forfait',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Utilisé uniquement si mode_calcul = FORFAIT', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='garantieacte',
            name='plafond_forfait',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Plafond max à appliquer même en mode forfait', max_digits=15, null=True),
        ),
    ]
